module Domain.StableSettlement exposing (stablePlan)

{-| Stable derivation of the settlement plan.

> WARNING: This module was fully generated by Opus 4.7.

Wraps `Domain.Settlement.computeSettlement` so that adding a Transfer event
between "anchor-mover" events (expense add/edit/delete, income, preference
change…) perturbs the displayed plan only locally rather than re-running the
greedy two-pass on the new balance vector.

The contract `stablePlan` honors:

  - **Equivalence at anchor.** When `current == anchor`, the result equals the
    plan `Settlement.computeSettlement` would have produced from the anchor —
    same edges in the same order.
  - **Flow feasibility.** For every member `n`,
    `(Σ out of n) − (Σ into n) = −current[n].netBalance`.
  - **Monotonic stability.** Growing `Δ_n = current[n] − anchor[n]` at a
    single node monotonically (i.e. extending a sequence of one-sided
    transfers) only extends or shrinks the same prefix of plan edges; edges
    untouched by `Δ` keep their original position in the list.

-}

import Dict exposing (Dict)
import Domain.Balance exposing (MemberBalance)
import Domain.Member as Member
import Domain.Settlement as Settlement
import Set


{-| Build the displayed plan from the anchor cache and the current balances.
-}
stablePlan :
    Dict Member.Id MemberBalance
    -> List Settlement.Preference
    -> Dict Member.Id MemberBalance
    -> List Settlement.Transaction
stablePlan anchorBalances preferences currentBalances =
    let
        delta : Dict Member.Id Int
        delta =
            balanceDelta anchorBalances currentBalances

        anchorPlan : List Settlement.Transaction
        anchorPlan =
            Settlement.computeSettlement anchorBalances preferences
    in
    applyVectorUpdate anchorPlan delta


{-| Per-member net change between two snapshots. Zero entries are dropped so
that downstream filters can rely on `Δ_n ≠ 0` for every key in the dict.
-}
balanceDelta :
    Dict Member.Id MemberBalance
    -> Dict Member.Id MemberBalance
    -> Dict Member.Id Int
balanceDelta anchor current =
    let
        keys : Set.Set Member.Id
        keys =
            Set.union
                (Set.fromList (Dict.keys anchor))
                (Set.fromList (Dict.keys current))

        netAt : Dict Member.Id MemberBalance -> Member.Id -> Int
        netAt d k =
            Dict.get k d
                |> Maybe.map .netBalance
                |> Maybe.withDefault 0
    in
    Set.foldl
        (\k acc ->
            let
                d : Int
                d =
                    netAt current k - netAt anchor k
            in
            if d == 0 then
                acc

            else
                Dict.insert k d acc
        )
        Dict.empty
        keys


type alias Edge =
    ( Member.Id, Member.Id, Int )


{-| Four-step vector flow update; see the module docs for the contract.

Classification of nodes by `Δ` sign drives the whole algorithm:

  - **payer** (`Δ_n > 0`): n's net balance went up, i.e. n paid out via one or
    more post-anchor transfers. The plan must lose `Δ_n` units of n's outgoing
    obligation.
  - **receiver** (`Δ_n < 0`): n's net balance went down, i.e. n received money.
    The plan must lose `|Δ_n|` units of n's incoming obligation.

Steps:

1.  **Step A** — for each (payer, receiver) pair connected by a direct plan
    edge `p→r`, consume `min(Δ_p, |Δ_r|, edge)` along it.

2.  **Phase 1** — each remaining payer drains its outgoing edges in canonical
    counterpart-id order. Drained amounts feed `lostIncoming` (creditors who
    expected money that now won't arrive). Exhausting `Δ_p` past all outgoing
    edges flips n into `newCreditors`.

3.  **Phase 2** — symmetrical for receivers; drained amounts feed
    `lostOutgoing`; overshoot flips n into `newDebtors`.

4.  **Phase 3** — pair residual supply (`lostOutgoing ∪ newDebtors`) with
    residual demand (`lostIncoming ∪ newCreditors`) in canonical order. Each
    match emits a bypass edge.

All per-node walks and the Phase 3 pairing use a fixed canonical id order, so
growing `Δ_n` monotonically only extends the already-consumed prefix instead
of reshuffling edges. To preserve the visible order of the displayed plan,
every step keeps the anchor-plan edges at their original list positions —
canonical order is used only to _decide_ drain amounts, not to _emit_ edges.

-}
applyVectorUpdate : List Settlement.Transaction -> Dict Member.Id Int -> List Settlement.Transaction
applyVectorUpdate plan delta0 =
    let
        edges0 : List Edge
        edges0 =
            List.map (\t -> ( t.from, t.to, t.amount )) plan

        ( edgesA, deltaADict ) =
            cancelDirectPairs edges0 delta0

        sortedDeltaA : List ( Member.Id, Int )
        sortedDeltaA =
            -- Already sorted list
            Dict.toList deltaADict

        payers : List ( Member.Id, Int )
        payers =
            sortedDeltaA
                |> List.filter (\( _, d ) -> d > 0)

        receivers : List ( Member.Id, Int )
        receivers =
            sortedDeltaA
                |> List.filter (\( _, d ) -> d < 0)

        ( edgesP1, lostIncoming, newCreditors ) =
            List.foldl drainOutgoing ( edgesA, Dict.empty, Dict.empty ) payers

        ( edgesP2, lostOutgoing, newDebtors ) =
            List.foldl drainIncoming ( edgesP1, Dict.empty, Dict.empty ) receivers

        supply : List ( Member.Id, Int )
        supply =
            mergeAmountDicts lostOutgoing newDebtors
                |> Dict.toList

        demand : List ( Member.Id, Int )
        demand =
            mergeAmountDicts lostIncoming newCreditors
                |> Dict.toList

        bypassEdges : List Edge
        bypassEdges =
            matchResiduals supply demand []
    in
    consolidateEdges (edgesP2 ++ bypassEdges)


{-| Walk all plan edges in canonical order; for each `(p, r)` where `p` is a
payer and `r` is a receiver, consume `min(Δ_p, |Δ_r|, amount)` along the edge.
The returned edge list preserves the original order — drain amounts are
recorded against indices and applied in place at the end.
-}
cancelDirectPairs : List Edge -> Dict Member.Id Int -> ( List Edge, Dict Member.Id Int )
cancelDirectPairs edges delta =
    let
        indexed : List ( Int, Edge )
        indexed =
            List.indexedMap Tuple.pair edges

        sorted : List ( Int, Edge )
        sorted =
            List.sortWith
                (\( _, e1 ) ( _, e2 ) -> edgeOrder e1 e2)
                indexed

        ( drainByIdx, finalDelta ) =
            List.foldl cancelOne ( Dict.empty, delta ) sorted
    in
    ( applyDrainByIdx drainByIdx edges, finalDelta )


cancelOne :
    ( Int, Edge )
    -> ( Dict Int Int, Dict Member.Id Int )
    -> ( Dict Int Int, Dict Member.Id Int )
cancelOne ( idx, ( f, t, amt ) ) ( drainByIdx, delta ) =
    let
        df : Int
        df =
            Dict.get f delta |> Maybe.withDefault 0

        dt : Int
        dt =
            Dict.get t delta |> Maybe.withDefault 0
    in
    if df > 0 && dt < 0 then
        let
            take : Int
            take =
                Basics.min (Basics.min df -dt) amt
        in
        ( Dict.insert idx take drainByIdx
        , delta
            |> setDelta f (df - take)
            |> setDelta t (dt + take)
        )

    else
        ( drainByIdx, delta )


edgeOrder : Edge -> Edge -> Order
edgeOrder ( f1, t1, _ ) ( f2, t2, _ ) =
    case compare f1 f2 of
        EQ ->
            compare t1 t2

        o ->
            o


setDelta : Member.Id -> Int -> Dict Member.Id Int -> Dict Member.Id Int
setDelta k v d =
    if v == 0 then
        Dict.remove k d

    else
        Dict.insert k v d


drainOutgoing :
    ( Member.Id, Int )
    -> ( List Edge, Dict Member.Id Int, Dict Member.Id Int )
    -> ( List Edge, Dict Member.Id Int, Dict Member.Id Int )
drainOutgoing ( n, dn ) ( edges, lostIncoming, newCreditors ) =
    let
        nOut : List ( Int, Edge )
        nOut =
            edges
                |> List.indexedMap Tuple.pair
                |> List.filter (\( _, ( f, _, _ ) ) -> f == n)
                |> List.sortBy (\( _, ( _, t, _ ) ) -> t)

        ( drainByIdx, remaining, drained ) =
            List.foldl
                (\( idx, ( _, t, amt ) ) ( dict, rem, accDrained ) ->
                    if rem <= 0 then
                        ( dict, rem, accDrained )

                    else
                        let
                            take : Int
                            take =
                                Basics.min rem amt
                        in
                        ( Dict.insert idx take dict
                        , rem - take
                        , ( t, take ) :: accDrained
                        )
                )
                ( Dict.empty, dn, [] )
                nOut
    in
    ( applyDrainByIdx drainByIdx edges
    , List.foldl (\( cid, amt ) -> addAmount cid amt) lostIncoming drained
    , if remaining > 0 then
        Dict.insert n remaining newCreditors

      else
        newCreditors
    )


drainIncoming :
    ( Member.Id, Int )
    -> ( List Edge, Dict Member.Id Int, Dict Member.Id Int )
    -> ( List Edge, Dict Member.Id Int, Dict Member.Id Int )
drainIncoming ( n, dn ) ( edges, lostOutgoing, newDebtors ) =
    let
        nIn : List ( Int, Edge )
        nIn =
            edges
                |> List.indexedMap Tuple.pair
                |> List.filter (\( _, ( _, t, _ ) ) -> t == n)
                |> List.sortBy (\( _, ( f, _, _ ) ) -> f)

        ( drainByIdx, remaining, drained ) =
            List.foldl
                (\( idx, ( f, _, amt ) ) ( dict, rem, accDrained ) ->
                    if rem <= 0 then
                        ( dict, rem, accDrained )

                    else
                        let
                            take : Int
                            take =
                                Basics.min rem amt
                        in
                        ( Dict.insert idx take dict
                        , rem - take
                        , ( f, take ) :: accDrained
                        )
                )
                ( Dict.empty, negate dn, [] )
                nIn
    in
    ( applyDrainByIdx drainByIdx edges
    , List.foldl (\( did, amt ) -> addAmount did amt) lostOutgoing drained
    , if remaining > 0 then
        Dict.insert n remaining newDebtors

      else
        newDebtors
    )


{-| Subtract per-index drain amounts from a list of edges, preserving order.
-}
applyDrainByIdx : Dict Int Int -> List Edge -> List Edge
applyDrainByIdx drainByIdx edges =
    List.indexedMap
        (\i (( f, t, amt ) as e) ->
            case Dict.get i drainByIdx of
                Just take ->
                    ( f, t, amt - take )

                Nothing ->
                    e
        )
        edges


addAmount : Member.Id -> Int -> Dict Member.Id Int -> Dict Member.Id Int
addAmount k v =
    Dict.update k
        (\mv ->
            case mv of
                Just cur ->
                    Just (cur + v)

                Nothing ->
                    Just v
        )


mergeAmountDicts : Dict Member.Id Int -> Dict Member.Id Int -> Dict Member.Id Int
mergeAmountDicts a b =
    Dict.foldl addAmount a b


{-| Pair earliest supplier with earliest demander; both lists must be sorted by
`Member.Id`. Their totals are equal because `Σ Δ = 0`.
-}
matchResiduals : List ( Member.Id, Int ) -> List ( Member.Id, Int ) -> List Edge -> List Edge
matchResiduals supply demand acc =
    case ( supply, demand ) of
        ( [], _ ) ->
            List.reverse acc

        ( _, [] ) ->
            List.reverse acc

        ( ( s, sAmt ) :: restS, ( d, dAmt ) :: restD ) ->
            let
                take : Int
                take =
                    Basics.min sAmt dAmt

                edge : Edge
                edge =
                    ( s, d, take )
            in
            case compare sAmt dAmt of
                EQ ->
                    matchResiduals restS restD (edge :: acc)

                LT ->
                    matchResiduals restS (( d, dAmt - take ) :: restD) (edge :: acc)

                GT ->
                    matchResiduals (( s, sAmt - take ) :: restS) restD (edge :: acc)


{-| Drop zero-amount edges and collapse duplicate `(from, to)` edges so that
bypass edges that happen to land on an existing edge merge into a single
entry. Output preserves the order in which each `(from, to)` first appears in
the input — when `Δ = 0` this keeps the greedy plan's edge order intact, which
is what the display layer expects.
-}
consolidateEdges : List Edge -> List Settlement.Transaction
consolidateEdges edges =
    let
        totals : Dict ( Member.Id, Member.Id ) Int
        totals =
            List.foldl
                (\( f, t, amt ) acc ->
                    Dict.update ( f, t )
                        (\mv ->
                            case mv of
                                Just cur ->
                                    Just (cur + amt)

                                Nothing ->
                                    Just amt
                        )
                        acc
                )
                Dict.empty
                edges

        firstOccurrences : List ( Member.Id, Member.Id )
        firstOccurrences =
            List.foldl
                (\( f, t, _ ) ( seen, acc ) ->
                    if Dict.member ( f, t ) seen then
                        ( seen, acc )

                    else
                        ( Dict.insert ( f, t ) () seen, ( f, t ) :: acc )
                )
                ( Dict.empty, [] )
                edges
                |> Tuple.second
                |> List.reverse
    in
    firstOccurrences
        |> List.filterMap
            (\( f, t ) ->
                Dict.get ( f, t ) totals
                    |> Maybe.andThen
                        (\amt ->
                            if amt > 0 then
                                Just { from = f, to = t, amount = amt }

                            else
                                Nothing
                        )
            )
