export default {
  id: "home",
  template: "home",
  negotiate: "/",
  slug: { en: "", fr: "" },
  en: {
    title: "Partage — Private, local-first bill splitting",
    description:
      "Partage is a free, open-source bill-splitting app. End-to-end encrypted, works offline, no account needed.",
    heading: "Welcome to Partage",
    tagline: "Private, encrypted bill splitting that works offline — no account needed.",
    open: "Open Partage",
    whyTitle: "Why Partage",
    whyBody:
      "Splitting bills with friends should be simple, and stay between you and your friends. Partage is end-to-end encrypted, works offline, and syncs across devices when you want.",
    featuresTitle: "Features",
    features: [
      ["lock", "End-to-end encrypted"],
      ["key", "No account or password"],
      ["wifi-off", "Works offline, syncs when online"],
      ["git-merge", "Smart settle-up with fewer transactions"],
      ["globe", "Multiple currencies in one group"],
      ["clock", "Full activity and edit history"],
      ["smartphone", "Installable on any device"],
      ["heart", "Open source, no ads, no user tracking"],
    ],
    screenshotsTitle: "A look inside",
    screenshots: [
      ["screenshot-balance.webp", "Balances and smart settle-up"],
      ["screenshot-multicurrency.webp", "Add expenses in any currency"],
      ["screenshot-activity.webp", "Full activity log with edit history"],
      ["screenshot-invite.webp", "Invite by link or QR code"],
    ],
    detailsTitle: "Details that matter",
    details: [
      ["filter", "Filter by person, category, currency, or date"],
      ["download", "Free CSV export and complete JSON backup"],
      ["credit-card", "Payment hints for common payment methods"],
      ["users", "Virtual members, merging, and retirement without lost history"],
      ["trending-up", "Expenses, transfers, and income"],
      ["rotate-ccw", "Soft deletion with restore and field-level edit history"],
      ["user-check", "Per-member settle-up preferences"],
      ["gift", "No daily limits, caps, or ads"],
    ],
    howTitle: "How it works",
    howBody:
      "Your expenses stay on your device and are encrypted before syncing. Only group members with the shared key can read them. The relay never receives the key or decrypted content.",
    fundingTitle: "Open source and funding",
    fundingBody:
      "Partage is free, open source, and ad-free. Running the sync relay costs a few cents per active user each month. If Partage helps you, please consider supporting it.",
    fundingCta: "Support Partage",
    about: "App information and local usage",
    source: "Source code",
    feedback: "Send feedback",
    whatsNew: "What’s new",
  },
  fr: {
    title: "Partage — Partage de frais privé et local-first",
    description:
      "Partage est une application libre et gratuite de partage de frais. Chiffrée de bout en bout, hors-ligne et sans compte.",
    heading: "Bienvenue sur Partage",
    tagline: "Le partage de frais privé et chiffré qui fonctionne hors-ligne — sans compte.",
    open: "Ouvrir Partage",
    whyTitle: "Pourquoi Partage",
    whyBody:
      "Partager les frais entre amis doit rester simple, et entre vous. Partage est chiffré de bout en bout, fonctionne hors-ligne et se synchronise entre appareils quand vous le souhaitez.",
    featuresTitle: "Fonctionnalités",
    features: [
      ["lock", "Chiffrement de bout en bout"],
      ["key", "Sans compte ni mot de passe"],
      ["wifi-off", "Hors-ligne, synchronisé en ligne"],
      ["git-merge", "Remboursements optimisés"],
      ["globe", "Plusieurs devises dans un groupe"],
      ["clock", "Journal complet des modifications"],
      ["smartphone", "Installable sur tout appareil"],
      ["heart", "Open source, sans pub ni suivi individuel"],
    ],
    screenshotsTitle: "Aperçu de l’application",
    screenshots: [
      ["screenshot-balance.webp", "Soldes et remboursements optimisés"],
      ["screenshot-multicurrency.webp", "Ajouter une dépense dans n’importe quelle devise"],
      ["screenshot-activity.webp", "Journal complet avec historique des modifications"],
      ["screenshot-invite.webp", "Inviter par lien ou QR code"],
    ],
    detailsTitle: "Les détails qui comptent",
    details: [
      ["filter", "Filtrer par personne, catégorie, devise ou date"],
      ["download", "Export CSV gratuit et sauvegarde JSON complète"],
      ["credit-card", "Raccourcis pour les moyens de remboursement courants"],
      ["users", "Membres virtuels, fusion et retrait sans perte d’historique"],
      ["trending-up", "Dépenses, transferts et revenus"],
      ["rotate-ccw", "Suppression réversible et historique détaillé"],
      ["user-check", "Préférences de remboursement par membre"],
      ["gift", "Sans limite journalière, plafond ni publicité"],
    ],
    howTitle: "Comment ça marche",
    howBody:
      "Vos dépenses restent sur votre appareil et sont chiffrées avant synchronisation. Seuls les membres ayant la clé du groupe peuvent les lire. Le relais ne reçoit jamais la clé ni le contenu déchiffré.",
    fundingTitle: "Open source et financement",
    fundingBody:
      "Partage est gratuit, open source et sans publicité. Le relais de synchronisation coûte quelques centimes par utilisateur actif chaque mois. Si Partage vous aide, vous pouvez le soutenir.",
    fundingCta: "Soutenir Partage",
    about: "Informations sur l’app et usage local",
    source: "Code source",
    feedback: "Envoyer un retour",
    whatsNew: "Nouveautés",
  },
};
